apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-nginx
  namespace: k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-nginx
  template:
    metadata:
      labels:
        app: color-nginx
    spec:
      containers:
      - name: color-nginx
        image: j4b3r/color-nginx:latest
        env:
        - name: COLOR
          value: "red"
        ports:
        - containerPort: 80
